<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Unofficial Solutions to R for Data Science</title>
  <meta name="description" content="This bookdown contains unofficial solutions to the exercises in R for Data Science written by Hadley Wickham and Garret Grolemund.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Unofficial Solutions to R for Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This bookdown contains unofficial solutions to the exercises in R for Data Science written by Hadley Wickham and Garret Grolemund." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Unofficial Solutions to R for Data Science" />
  
  <meta name="twitter:description" content="This bookdown contains unofficial solutions to the exercises in R for Data Science written by Hadley Wickham and Garret Grolemund." />
  

<meta name="author" content="Lok H. Chau">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="workflow-basics.html">
<link rel="next" href="workflow-scripts.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.0/htmlwidgets.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.2.0/str_view.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Unoffical Solutions to R4DS</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="part"><span><b>I Explore</b></span></li>
<li class="chapter" data-level="2" data-path="introduction-1.html"><a href="introduction-1.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>3</b> Data visualization</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualization.html"><a href="data-visualization.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualization.html"><a href="data-visualization.html#first-steps"><i class="fa fa-check"></i><b>3.2</b> First steps</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises"><i class="fa fa-check"></i><b>3.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-visualization.html"><a href="data-visualization.html#aesthetic-mappings"><i class="fa fa-check"></i><b>3.3</b> Aesthetic mappings</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises-1"><i class="fa fa-check"></i><b>3.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-visualization.html"><a href="data-visualization.html#common-problems"><i class="fa fa-check"></i><b>3.4</b> Common problems</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualization.html"><a href="data-visualization.html#facets"><i class="fa fa-check"></i><b>3.5</b> Facets</a><ul>
<li class="chapter" data-level="3.5.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises-2"><i class="fa fa-check"></i><b>3.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-visualization.html"><a href="data-visualization.html#geometric-objects"><i class="fa fa-check"></i><b>3.6</b> Geometric objects</a><ul>
<li class="chapter" data-level="3.6.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises-3"><i class="fa fa-check"></i><b>3.6.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-visualization.html"><a href="data-visualization.html#statistical-transformations"><i class="fa fa-check"></i><b>3.7</b> Statistical transformations</a><ul>
<li class="chapter" data-level="3.7.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises-4"><i class="fa fa-check"></i><b>3.7.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data-visualization.html"><a href="data-visualization.html#position-adjustments"><i class="fa fa-check"></i><b>3.8</b> Position adjustments</a><ul>
<li class="chapter" data-level="3.8.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises-5"><i class="fa fa-check"></i><b>3.8.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data-visualization.html"><a href="data-visualization.html#coordinate-systems"><i class="fa fa-check"></i><b>3.9</b> Coordinate systems</a><ul>
<li class="chapter" data-level="3.9.1" data-path="data-visualization.html"><a href="data-visualization.html#exercises-6"><i class="fa fa-check"></i><b>3.9.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="data-visualization.html"><a href="data-visualization.html#the-layered-grammar-of-graphics"><i class="fa fa-check"></i><b>3.10</b> The layered grammar of graphics</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="workflow-basics.html"><a href="workflow-basics.html"><i class="fa fa-check"></i><b>4</b> Workflow Basics</a><ul>
<li class="chapter" data-level="4.1" data-path="workflow-basics.html"><a href="workflow-basics.html#coding-basics"><i class="fa fa-check"></i><b>4.1</b> Coding basics</a></li>
<li class="chapter" data-level="4.2" data-path="workflow-basics.html"><a href="workflow-basics.html#whats-in-a-name"><i class="fa fa-check"></i><b>4.2</b> What’s in a name?</a></li>
<li class="chapter" data-level="4.3" data-path="workflow-basics.html"><a href="workflow-basics.html#calling-functions"><i class="fa fa-check"></i><b>4.3</b> Calling functions</a></li>
<li class="chapter" data-level="4.4" data-path="workflow-basics.html"><a href="workflow-basics.html#practice"><i class="fa fa-check"></i><b>4.4</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>5</b> Data transformation</a><ul>
<li class="chapter" data-level="5.1" data-path="data-transformation.html"><a href="data-transformation.html#introduction-3"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="data-transformation.html"><a href="data-transformation.html#filter-rows-with-filter"><i class="fa fa-check"></i><b>5.2</b> Filter rows with <code>filter()</code></a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-transformation.html"><a href="data-transformation.html#exercises-7"><i class="fa fa-check"></i><b>5.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformation.html"><a href="data-transformation.html#arrange-rows-with-arrange"><i class="fa fa-check"></i><b>5.3</b> Arrange rows with <code>arrange()</code></a><ul>
<li class="chapter" data-level="5.3.1" data-path="data-transformation.html"><a href="data-transformation.html#exercises-8"><i class="fa fa-check"></i><b>5.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="data-transformation.html"><a href="data-transformation.html#select-columns-with-select"><i class="fa fa-check"></i><b>5.4</b> Select columns with <code>select()</code></a><ul>
<li class="chapter" data-level="5.4.1" data-path="data-transformation.html"><a href="data-transformation.html#exercises-9"><i class="fa fa-check"></i><b>5.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="data-transformation.html"><a href="data-transformation.html#add-new-variables-with-mutate"><i class="fa fa-check"></i><b>5.5</b> Add new variables with <code>mutate()</code></a><ul>
<li class="chapter" data-level="5.5.1" data-path="data-transformation.html"><a href="data-transformation.html#exercises-10"><i class="fa fa-check"></i><b>5.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="data-transformation.html"><a href="data-transformation.html#grouped-summaries-with-summarise"><i class="fa fa-check"></i><b>5.6</b> Grouped summaries with <code>summarise()</code></a><ul>
<li class="chapter" data-level="5.6.1" data-path="data-transformation.html"><a href="data-transformation.html#exercises-11"><i class="fa fa-check"></i><b>5.6.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="data-transformation.html"><a href="data-transformation.html#grouped-mutates-and-filters"><i class="fa fa-check"></i><b>5.7</b> Grouped mutates (and filters)</a><ul>
<li class="chapter" data-level="5.7.1" data-path="data-transformation.html"><a href="data-transformation.html#exercises-12"><i class="fa fa-check"></i><b>5.7.1</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="workflow-scripts.html"><a href="workflow-scripts.html"><i class="fa fa-check"></i><b>6</b> Workflow: scripts</a></li>
<li class="chapter" data-level="7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html"><i class="fa fa-check"></i><b>7</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#introduction-4"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#questions"><i class="fa fa-check"></i><b>7.2</b> Questions</a></li>
<li class="chapter" data-level="7.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#variation"><i class="fa fa-check"></i><b>7.3</b> Variation</a><ul>
<li class="chapter" data-level="7.3.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#exercises-13"><i class="fa fa-check"></i><b>7.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#missing-values"><i class="fa fa-check"></i><b>7.4</b> Missing values</a><ul>
<li class="chapter" data-level="7.4.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#exercises-14"><i class="fa fa-check"></i><b>7.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#covariation"><i class="fa fa-check"></i><b>7.5</b> Covariation</a><ul>
<li class="chapter" data-level="7.5.1" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#a-categorical-and-continuous-variable"><i class="fa fa-check"></i><b>7.5.1</b> A categorical and continuous variable</a></li>
<li class="chapter" data-level="7.5.2" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#two-categorical-variables"><i class="fa fa-check"></i><b>7.5.2</b> Two categorical variables</a></li>
<li class="chapter" data-level="7.5.3" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#two-continuous-variables"><i class="fa fa-check"></i><b>7.5.3</b> Two continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#patterns-and-models"><i class="fa fa-check"></i><b>7.6</b> Patterns and models</a></li>
<li class="chapter" data-level="7.7" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#ggplot2-calls"><i class="fa fa-check"></i><b>7.7</b> ggplot2 calls</a></li>
<li class="chapter" data-level="7.8" data-path="exploratory-data-analysis.html"><a href="exploratory-data-analysis.html#learning-more"><i class="fa fa-check"></i><b>7.8</b> Learning more</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="workflow-projects.html"><a href="workflow-projects.html"><i class="fa fa-check"></i><b>8</b> Workflow: projects</a></li>
<li class="part"><span><b>II Wrangle</b></span></li>
<li class="chapter" data-level="9" data-path="introduction-5.html"><a href="introduction-5.html"><i class="fa fa-check"></i><b>9</b> Introduction</a></li>
<li class="chapter" data-level="10" data-path="tibbles.html"><a href="tibbles.html"><i class="fa fa-check"></i><b>10</b> Tibbles</a><ul>
<li class="chapter" data-level="10.1" data-path="tibbles.html"><a href="tibbles.html#introduction-6"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="tibbles.html"><a href="tibbles.html#creating-tibbles"><i class="fa fa-check"></i><b>10.2</b> Creating tibbles</a></li>
<li class="chapter" data-level="10.3" data-path="tibbles.html"><a href="tibbles.html#tibbles-vs.data.frame"><i class="fa fa-check"></i><b>10.3</b> Tibbles vs. data.frame</a></li>
<li class="chapter" data-level="10.4" data-path="tibbles.html"><a href="tibbles.html#interacting-with-older-code"><i class="fa fa-check"></i><b>10.4</b> Interacting with older code</a></li>
<li class="chapter" data-level="10.5" data-path="tibbles.html"><a href="tibbles.html#exercises-18"><i class="fa fa-check"></i><b>10.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="data-import.html"><a href="data-import.html"><i class="fa fa-check"></i><b>11</b> Data Import</a><ul>
<li class="chapter" data-level="11.1" data-path="data-import.html"><a href="data-import.html#introduction-7"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="data-import.html"><a href="data-import.html#getting-started"><i class="fa fa-check"></i><b>11.2</b> Getting started</a><ul>
<li class="chapter" data-level="11.2.1" data-path="data-import.html"><a href="data-import.html#exercises-19"><i class="fa fa-check"></i><b>11.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="data-import.html"><a href="data-import.html#parsing-a-vector"><i class="fa fa-check"></i><b>11.3</b> Parsing a vector</a><ul>
<li class="chapter" data-level="11.3.1" data-path="data-import.html"><a href="data-import.html#exercises-20"><i class="fa fa-check"></i><b>11.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="data-import.html"><a href="data-import.html#parsing-a-file"><i class="fa fa-check"></i><b>11.4</b> Parsing a file</a></li>
<li class="chapter" data-level="11.5" data-path="data-import.html"><a href="data-import.html#writing-to-a-file"><i class="fa fa-check"></i><b>11.5</b> Writing to a file</a></li>
<li class="chapter" data-level="11.6" data-path="data-import.html"><a href="data-import.html#other-types-of-data"><i class="fa fa-check"></i><b>11.6</b> Other types of data</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="tidy-data.html"><a href="tidy-data.html"><i class="fa fa-check"></i><b>12</b> Tidy data</a><ul>
<li class="chapter" data-level="12.1" data-path="tidy-data.html"><a href="tidy-data.html#introduction-8"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="tidy-data.html"><a href="tidy-data.html#tidy-data-1"><i class="fa fa-check"></i><b>12.2</b> Tidy data</a><ul>
<li class="chapter" data-level="12.2.1" data-path="tidy-data.html"><a href="tidy-data.html#exercises-21"><i class="fa fa-check"></i><b>12.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="tidy-data.html"><a href="tidy-data.html#spreading-and-gathering"><i class="fa fa-check"></i><b>12.3</b> Spreading and gathering</a><ul>
<li class="chapter" data-level="12.3.1" data-path="tidy-data.html"><a href="tidy-data.html#exercises-22"><i class="fa fa-check"></i><b>12.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="tidy-data.html"><a href="tidy-data.html#separating-and-uniting"><i class="fa fa-check"></i><b>12.4</b> Separating and uniting</a><ul>
<li class="chapter" data-level="12.4.1" data-path="tidy-data.html"><a href="tidy-data.html#exercises-23"><i class="fa fa-check"></i><b>12.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="tidy-data.html"><a href="tidy-data.html#missing-values-1"><i class="fa fa-check"></i><b>12.5</b> Missing values</a><ul>
<li class="chapter" data-level="12.5.1" data-path="tidy-data.html"><a href="tidy-data.html#exercises-24"><i class="fa fa-check"></i><b>12.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="tidy-data.html"><a href="tidy-data.html#case-study"><i class="fa fa-check"></i><b>12.6</b> Case Study</a><ul>
<li class="chapter" data-level="12.6.1" data-path="tidy-data.html"><a href="tidy-data.html#exercises-25"><i class="fa fa-check"></i><b>12.6.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="tidy-data.html"><a href="tidy-data.html#non-tidy-data"><i class="fa fa-check"></i><b>12.7</b> Non-tidy data</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="relational-data.html"><a href="relational-data.html"><i class="fa fa-check"></i><b>13</b> Relational data</a><ul>
<li class="chapter" data-level="13.1" data-path="relational-data.html"><a href="relational-data.html#introduction-9"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="relational-data.html"><a href="relational-data.html#nycflights13"><i class="fa fa-check"></i><b>13.2</b> nycflights13</a><ul>
<li class="chapter" data-level="13.2.1" data-path="relational-data.html"><a href="relational-data.html#exercises-26"><i class="fa fa-check"></i><b>13.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="relational-data.html"><a href="relational-data.html#keys"><i class="fa fa-check"></i><b>13.3</b> Keys</a><ul>
<li class="chapter" data-level="13.3.1" data-path="relational-data.html"><a href="relational-data.html#exercises-27"><i class="fa fa-check"></i><b>13.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="relational-data.html"><a href="relational-data.html#mutating-joins"><i class="fa fa-check"></i><b>13.4</b> Mutating joins</a><ul>
<li class="chapter" data-level="13.4.1" data-path="relational-data.html"><a href="relational-data.html#exercises-28"><i class="fa fa-check"></i><b>13.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="relational-data.html"><a href="relational-data.html#filtering-joins"><i class="fa fa-check"></i><b>13.5</b> Filtering joins</a><ul>
<li class="chapter" data-level="13.5.1" data-path="relational-data.html"><a href="relational-data.html#exercises-29"><i class="fa fa-check"></i><b>13.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="relational-data.html"><a href="relational-data.html#join-problems"><i class="fa fa-check"></i><b>13.6</b> Join problems</a></li>
<li class="chapter" data-level="13.7" data-path="relational-data.html"><a href="relational-data.html#set-operations"><i class="fa fa-check"></i><b>13.7</b> Set operations</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>14</b> Strings</a><ul>
<li class="chapter" data-level="14.1" data-path="strings.html"><a href="strings.html#introduction-10"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="strings.html"><a href="strings.html#string-basics"><i class="fa fa-check"></i><b>14.2</b> String basics</a><ul>
<li class="chapter" data-level="14.2.1" data-path="strings.html"><a href="strings.html#exercises-30"><i class="fa fa-check"></i><b>14.2.1</b> Exercises</a></li>
<li class="chapter" data-level="14.2.2" data-path="strings.html"><a href="strings.html#matching-patterns-with-regular-expressions"><i class="fa fa-check"></i><b>14.2.2</b> Matching patterns with regular expressions</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="strings.html"><a href="strings.html#tools"><i class="fa fa-check"></i><b>14.3</b> Tools</a><ul>
<li class="chapter" data-level="14.3.1" data-path="strings.html"><a href="strings.html#detect-matches"><i class="fa fa-check"></i><b>14.3.1</b> Detect matches</a></li>
<li class="chapter" data-level="14.3.2" data-path="strings.html"><a href="strings.html#exercises-31"><i class="fa fa-check"></i><b>14.3.2</b> Exercises</a></li>
<li class="chapter" data-level="14.3.3" data-path="strings.html"><a href="strings.html#extract-matches"><i class="fa fa-check"></i><b>14.3.3</b> Extract matches</a></li>
<li class="chapter" data-level="14.3.4" data-path="strings.html"><a href="strings.html#grouped-matches"><i class="fa fa-check"></i><b>14.3.4</b> Grouped matches</a></li>
<li class="chapter" data-level="14.3.5" data-path="strings.html"><a href="strings.html#replacing-matches"><i class="fa fa-check"></i><b>14.3.5</b> Replacing matches</a></li>
<li class="chapter" data-level="14.3.6" data-path="strings.html"><a href="strings.html#splitting"><i class="fa fa-check"></i><b>14.3.6</b> Splitting</a></li>
<li class="chapter" data-level="14.3.7" data-path="strings.html"><a href="strings.html#find-matches"><i class="fa fa-check"></i><b>14.3.7</b> Find matches</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="strings.html"><a href="strings.html#other-types-of-pattern"><i class="fa fa-check"></i><b>14.4</b> Other types of pattern</a><ul>
<li class="chapter" data-level="14.4.1" data-path="strings.html"><a href="strings.html#exercises-36"><i class="fa fa-check"></i><b>14.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="strings.html"><a href="strings.html#other-uses-of-regular-expressions"><i class="fa fa-check"></i><b>14.5</b> Other uses of regular expressions</a></li>
<li class="chapter" data-level="14.6" data-path="strings.html"><a href="strings.html#stringi"><i class="fa fa-check"></i><b>14.6</b> stringi</a><ul>
<li class="chapter" data-level="14.6.1" data-path="strings.html"><a href="strings.html#exercises-37"><i class="fa fa-check"></i><b>14.6.1</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>15</b> Factors</a><ul>
<li class="chapter" data-level="15.1" data-path="factors.html"><a href="factors.html#introduction-11"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="factors.html"><a href="factors.html#creating-factors"><i class="fa fa-check"></i><b>15.2</b> Creating factors</a></li>
<li class="chapter" data-level="15.3" data-path="factors.html"><a href="factors.html#general-social-survey"><i class="fa fa-check"></i><b>15.3</b> General Social Survey</a><ul>
<li class="chapter" data-level="15.3.1" data-path="factors.html"><a href="factors.html#exercise"><i class="fa fa-check"></i><b>15.3.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="factors.html"><a href="factors.html#modifying-factor-order"><i class="fa fa-check"></i><b>15.4</b> Modifying factor order</a><ul>
<li class="chapter" data-level="15.4.1" data-path="factors.html"><a href="factors.html#exercises-38"><i class="fa fa-check"></i><b>15.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="factors.html"><a href="factors.html#modifying-factor-levels"><i class="fa fa-check"></i><b>15.5</b> Modifying factor levels</a><ul>
<li class="chapter" data-level="15.5.1" data-path="factors.html"><a href="factors.html#exercises-39"><i class="fa fa-check"></i><b>15.5.1</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="dates-and-times.html"><a href="dates-and-times.html"><i class="fa fa-check"></i><b>16</b> Dates and times</a><ul>
<li class="chapter" data-level="16.1" data-path="dates-and-times.html"><a href="dates-and-times.html#introduction-12"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="dates-and-times.html"><a href="dates-and-times.html#creating-datetimes"><i class="fa fa-check"></i><b>16.2</b> Creating date/times</a><ul>
<li class="chapter" data-level="16.2.1" data-path="dates-and-times.html"><a href="dates-and-times.html#exercises-40"><i class="fa fa-check"></i><b>16.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="dates-and-times.html"><a href="dates-and-times.html#date-time-components"><i class="fa fa-check"></i><b>16.3</b> Date-time components</a><ul>
<li class="chapter" data-level="16.3.1" data-path="dates-and-times.html"><a href="dates-and-times.html#exercises-41"><i class="fa fa-check"></i><b>16.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="dates-and-times.html"><a href="dates-and-times.html#time-spans"><i class="fa fa-check"></i><b>16.4</b> Time spans</a><ul>
<li class="chapter" data-level="16.4.1" data-path="dates-and-times.html"><a href="dates-and-times.html#exercises-42"><i class="fa fa-check"></i><b>16.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="dates-and-times.html"><a href="dates-and-times.html#time-zones"><i class="fa fa-check"></i><b>16.5</b> Time zones</a></li>
</ul></li>
<li class="part"><span><b>III Program</b></span></li>
<li class="chapter" data-level="17" data-path="introduction-13.html"><a href="introduction-13.html"><i class="fa fa-check"></i><b>17</b> Introduction</a></li>
<li class="chapter" data-level="18" data-path="pipes.html"><a href="pipes.html"><i class="fa fa-check"></i><b>18</b> Pipes</a></li>
<li class="chapter" data-level="19" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>19</b> Functions</a><ul>
<li class="chapter" data-level="19.1" data-path="functions.html"><a href="functions.html#introduction-14"><i class="fa fa-check"></i><b>19.1</b> Introduction</a></li>
<li class="chapter" data-level="19.2" data-path="functions.html"><a href="functions.html#when-should-you-write-a-function"><i class="fa fa-check"></i><b>19.2</b> When should you write a function?</a><ul>
<li class="chapter" data-level="19.2.1" data-path="functions.html"><a href="functions.html#practice-1"><i class="fa fa-check"></i><b>19.2.1</b> Practice</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="functions.html"><a href="functions.html#functions-are-for-humans-and-computers"><i class="fa fa-check"></i><b>19.3</b> Functions are for humans and computers</a><ul>
<li class="chapter" data-level="19.3.1" data-path="functions.html"><a href="functions.html#exercises-43"><i class="fa fa-check"></i><b>19.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="functions.html"><a href="functions.html#conditional-execution"><i class="fa fa-check"></i><b>19.4</b> Conditional execution</a><ul>
<li class="chapter" data-level="19.4.1" data-path="functions.html"><a href="functions.html#exercises-44"><i class="fa fa-check"></i><b>19.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="functions.html"><a href="functions.html#function-arguments"><i class="fa fa-check"></i><b>19.5</b> Function arguments</a><ul>
<li class="chapter" data-level="19.5.1" data-path="functions.html"><a href="functions.html#exercises-45"><i class="fa fa-check"></i><b>19.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="functions.html"><a href="functions.html#return-values"><i class="fa fa-check"></i><b>19.6</b> Return values</a></li>
<li class="chapter" data-level="19.7" data-path="functions.html"><a href="functions.html#environment"><i class="fa fa-check"></i><b>19.7</b> Environment</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="vectors.html"><a href="vectors.html"><i class="fa fa-check"></i><b>20</b> Vectors</a><ul>
<li class="chapter" data-level="20.1" data-path="vectors.html"><a href="vectors.html#introduction-15"><i class="fa fa-check"></i><b>20.1</b> Introduction</a></li>
<li class="chapter" data-level="20.2" data-path="vectors.html"><a href="vectors.html#vector-basics"><i class="fa fa-check"></i><b>20.2</b> Vector basics</a></li>
<li class="chapter" data-level="20.3" data-path="vectors.html"><a href="vectors.html#important-types-of-atomic-vector"><i class="fa fa-check"></i><b>20.3</b> Important types of atomic vector</a><ul>
<li class="chapter" data-level="20.3.1" data-path="vectors.html"><a href="vectors.html#exercises-46"><i class="fa fa-check"></i><b>20.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="vectors.html"><a href="vectors.html#using-atomic-vectors"><i class="fa fa-check"></i><b>20.4</b> Using atomic vectors</a><ul>
<li class="chapter" data-level="20.4.1" data-path="vectors.html"><a href="vectors.html#exercises-47"><i class="fa fa-check"></i><b>20.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="vectors.html"><a href="vectors.html#recursive-vectors-lists"><i class="fa fa-check"></i><b>20.5</b> Recursive vectors (lists)</a><ul>
<li class="chapter" data-level="20.5.1" data-path="vectors.html"><a href="vectors.html#exercise-1"><i class="fa fa-check"></i><b>20.5.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="vectors.html"><a href="vectors.html#attributes"><i class="fa fa-check"></i><b>20.6</b> Attributes</a></li>
<li class="chapter" data-level="20.7" data-path="vectors.html"><a href="vectors.html#augmented-vectors"><i class="fa fa-check"></i><b>20.7</b> Augmented vectors</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="iteration.html"><a href="iteration.html"><i class="fa fa-check"></i><b>21</b> Iteration</a><ul>
<li class="chapter" data-level="21.1" data-path="iteration.html"><a href="iteration.html#introduction-16"><i class="fa fa-check"></i><b>21.1</b> Introduction</a></li>
<li class="chapter" data-level="21.2" data-path="iteration.html"><a href="iteration.html#for-loops"><i class="fa fa-check"></i><b>21.2</b> For loops</a><ul>
<li class="chapter" data-level="21.2.1" data-path="iteration.html"><a href="iteration.html#exercises-48"><i class="fa fa-check"></i><b>21.2.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="iteration.html"><a href="iteration.html#for-loop-variations"><i class="fa fa-check"></i><b>21.3</b> For loop variations</a><ul>
<li class="chapter" data-level="21.3.1" data-path="iteration.html"><a href="iteration.html#exercises-49"><i class="fa fa-check"></i><b>21.3.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="iteration.html"><a href="iteration.html#for-loops-vs.functionals"><i class="fa fa-check"></i><b>21.4</b> For loops vs. functionals</a><ul>
<li class="chapter" data-level="21.4.1" data-path="iteration.html"><a href="iteration.html#exercises-50"><i class="fa fa-check"></i><b>21.4.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="iteration.html"><a href="iteration.html#the-map-functions"><i class="fa fa-check"></i><b>21.5</b> The map functions</a><ul>
<li class="chapter" data-level="21.5.1" data-path="iteration.html"><a href="iteration.html#exercises-51"><i class="fa fa-check"></i><b>21.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="iteration.html"><a href="iteration.html#dealing-with-failure"><i class="fa fa-check"></i><b>21.6</b> Dealing with failure</a></li>
<li class="chapter" data-level="21.7" data-path="iteration.html"><a href="iteration.html#mapping-over-multiple-arguments"><i class="fa fa-check"></i><b>21.7</b> Mapping over multiple arguments</a></li>
<li class="chapter" data-level="21.8" data-path="iteration.html"><a href="iteration.html#walk"><i class="fa fa-check"></i><b>21.8</b> Walk</a></li>
<li class="chapter" data-level="21.9" data-path="iteration.html"><a href="iteration.html#other-patterns-of-for-loops"><i class="fa fa-check"></i><b>21.9</b> Other patterns of for loops</a><ul>
<li class="chapter" data-level="21.9.1" data-path="iteration.html"><a href="iteration.html#exercises-52"><i class="fa fa-check"></i><b>21.9.1</b> Exercises</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Model</b></span></li>
<li class="chapter" data-level="22" data-path="introduction-17.html"><a href="introduction-17.html"><i class="fa fa-check"></i><b>22</b> Introduction</a></li>
<li class="part"><span><b>V Communicate</b></span></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Unofficial Solutions to R for Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-transformation" class="section level1">
<h1><span class="header-section-number">5</span> Data transformation</h1>
<div id="introduction-3" class="section level2">
<h2><span class="header-section-number">5.1</span> Introduction</h2>
<p>No exercises.</p>
</div>
<div id="filter-rows-with-filter" class="section level2">
<h2><span class="header-section-number">5.2</span> Filter rows with <code>filter()</code></h2>
<div id="exercises-7" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Exercises</h3>
<p><em>1 - Find all flights that</em></p>
<p><em>1. Had an arrival delay of two or more hours</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)

flights &lt;-<span class="st"> </span>nycflights13<span class="op">::</span>flights

<span class="kw">filter</span>(flights, arr_delay <span class="op">&gt;=</span><span class="st"> </span><span class="dv">120</span>)</code></pre></div>
<pre><code>## # A tibble: 10,200 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1      811            630     101       1047
##  2  2013     1     1      848           1835     853       1001
##  3  2013     1     1      957            733     144       1056
##  4  2013     1     1     1114            900     134       1447
##  5  2013     1     1     1505           1310     115       1638
##  6  2013     1     1     1525           1340     105       1831
##  7  2013     1     1     1549           1445      64.0     1912
##  8  2013     1     1     1558           1359     119       1718
##  9  2013     1     1     1732           1630      62.0     2028
## 10  2013     1     1     1803           1620     103       2008
## # ... with 10,190 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>2. Flew to Houston (<code>IAH</code> or <code>HOU</code>)</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, dest <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;IAH&#39;</span>, <span class="st">&#39;HOU&#39;</span>))</code></pre></div>
<pre><code>## # A tibble: 9,313 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1      517            515      2.00      830
##  2  2013     1     1      533            529      4.00      850
##  3  2013     1     1      623            627   -  4.00      933
##  4  2013     1     1      728            732   -  4.00     1041
##  5  2013     1     1      739            739      0        1104
##  6  2013     1     1      908            908      0        1228
##  7  2013     1     1     1028           1026      2.00     1350
##  8  2013     1     1     1044           1045   -  1.00     1352
##  9  2013     1     1     1114            900    134        1447
## 10  2013     1     1     1205           1200      5.00     1503
## # ... with 9,303 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>3. Were operated by United, American, or Delta</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, carrier <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;UA&#39;</span>,<span class="st">&#39;AA&#39;</span>,<span class="st">&#39;DL&#39;</span>))</code></pre></div>
<pre><code>## # A tibble: 139,504 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1      517            515      2.00      830
##  2  2013     1     1      533            529      4.00      850
##  3  2013     1     1      542            540      2.00      923
##  4  2013     1     1      554            600     -6.00      812
##  5  2013     1     1      554            558     -4.00      740
##  6  2013     1     1      558            600     -2.00      753
##  7  2013     1     1      558            600     -2.00      924
##  8  2013     1     1      558            600     -2.00      923
##  9  2013     1     1      559            600     -1.00      941
## 10  2013     1     1      559            600     -1.00      854
## # ... with 139,494 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>4. Departed in summer (July, August, and September)</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, month <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>))</code></pre></div>
<pre><code>## # A tibble: 86,326 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     7     1        1           2029    212         236
##  2  2013     7     1        2           2359      3.00      344
##  3  2013     7     1       29           2245    104         151
##  4  2013     7     1       43           2130    193         322
##  5  2013     7     1       44           2150    174         300
##  6  2013     7     1       46           2051    235         304
##  7  2013     7     1       48           2001    287         308
##  8  2013     7     1       58           2155    183         335
##  9  2013     7     1      100           2146    194         327
## 10  2013     7     1      100           2245    135         337
## # ... with 86,316 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>5. Arrived more than two hours late, but didn’t leave late</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, dep_delay <span class="op">&lt;=</span><span class="st"> </span><span class="dv">0</span>, arr_delay <span class="op">&gt;=</span><span class="st"> </span><span class="dv">120</span>)</code></pre></div>
<pre><code>## # A tibble: 29 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1    27     1419           1420     -1.00     1754
##  2  2013    10     7     1350           1350      0        1736
##  3  2013    10     7     1357           1359     -2.00     1858
##  4  2013    10    16      657            700     -3.00     1258
##  5  2013    11     1      658            700     -2.00     1329
##  6  2013     3    18     1844           1847     -3.00       39
##  7  2013     4    17     1635           1640     -5.00     2049
##  8  2013     4    18      558            600     -2.00     1149
##  9  2013     4    18      655            700     -5.00     1213
## 10  2013     5    22     1827           1830     -3.00     2217
## # ... with 19 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>6. Were delayed by at least an hour, but made up over 30 minutes in flight</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, dep_delay <span class="op">&gt;=</span><span class="st"> </span><span class="dv">60</span>, dep_delay <span class="op">&gt;</span><span class="st"> </span>arr_delay <span class="op">+</span><span class="st"> </span><span class="dv">30</span>)</code></pre></div>
<pre><code>## # A tibble: 1,844 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1     2205           1720     285         46
##  2  2013     1     1     2326           2130     116        131
##  3  2013     1     3     1503           1221     162       1803
##  4  2013     1     3     1839           1700      99.0     2056
##  5  2013     1     3     1850           1745      65.0     2148
##  6  2013     1     3     1941           1759     102       2246
##  7  2013     1     3     1950           1845      65.0     2228
##  8  2013     1     3     2015           1915      60.0     2135
##  9  2013     1     3     2257           2000     177         45
## 10  2013     1     4     1917           1700     137       2135
## # ... with 1,834 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>7. Departed between midnight and 6am (inclusive)</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, dep_time <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span>, dep_time <span class="op">&lt;=</span><span class="st"> </span><span class="dv">600</span>)</code></pre></div>
<pre><code>## # A tibble: 9,344 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1      517            515      2.00      830
##  2  2013     1     1      533            529      4.00      850
##  3  2013     1     1      542            540      2.00      923
##  4  2013     1     1      544            545     -1.00     1004
##  5  2013     1     1      554            600     -6.00      812
##  6  2013     1     1      554            558     -4.00      740
##  7  2013     1     1      555            600     -5.00      913
##  8  2013     1     1      557            600     -3.00      709
##  9  2013     1     1      557            600     -3.00      838
## 10  2013     1     1      558            600     -2.00      753
## # ... with 9,334 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>2 - Another useful dplyr filtering helper is <code>between()</code>. What does it do? Can you use it to simplify the code needed to answer the previous challenges?</em></p>
<p><code>between()</code> is a shortcut for <code>x &gt;= left &amp; x &lt;= right</code>. Part 7 of the previous question can be rewritten as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, <span class="kw">between</span>(dep_time, <span class="dv">0</span> , <span class="dv">600</span>))</code></pre></div>
<pre><code>## # A tibble: 9,344 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1      517            515      2.00      830
##  2  2013     1     1      533            529      4.00      850
##  3  2013     1     1      542            540      2.00      923
##  4  2013     1     1      544            545     -1.00     1004
##  5  2013     1     1      554            600     -6.00      812
##  6  2013     1     1      554            558     -4.00      740
##  7  2013     1     1      555            600     -5.00      913
##  8  2013     1     1      557            600     -3.00      709
##  9  2013     1     1      557            600     -3.00      838
## 10  2013     1     1      558            600     -2.00      753
## # ... with 9,334 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>3 - How many flights have a missing <code>dep_time</code>? What other variables are missing? What might these rows represent?</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">is.na</span>(flights<span class="op">$</span>dep_time))</code></pre></div>
<pre><code>## [1] 8255</code></pre>
<p>There are 8255 flights with missing <code>dep_time</code>. For the flights with missing <code>dep_time</code>, <code>dep_delay</code>, <code>arr_time</code>, <code>arr_delay</code>, and <code>air_time</code> are also missing. It means that these are the flights that were cancelled.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(flights, <span class="kw">is.na</span>(dep_time))</code></pre></div>
<pre><code>## # A tibble: 8,255 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     1       NA           1630        NA       NA
##  2  2013     1     1       NA           1935        NA       NA
##  3  2013     1     1       NA           1500        NA       NA
##  4  2013     1     1       NA            600        NA       NA
##  5  2013     1     2       NA           1540        NA       NA
##  6  2013     1     2       NA           1620        NA       NA
##  7  2013     1     2       NA           1355        NA       NA
##  8  2013     1     2       NA           1420        NA       NA
##  9  2013     1     2       NA           1321        NA       NA
## 10  2013     1     2       NA           1545        NA       NA
## # ... with 8,245 more rows, and 12 more variables: sched_arr_time &lt;int&gt;,
## #   arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;,
## #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,
## #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p><em>4 - Why is <code>NA ^ 0</code> not missing? Why is <code>NA | TRUE</code> not missing? Why is <code>FALSE &amp; NA not</code> missing? Can you figure out the general rule? (<code>NA \* 0</code> is a tricky counterexample!)</em></p>
<p>One way to think of <code>NA</code> is that it can be a placeholder for any possible values. By this logic:</p>
<ul>
<li>any values raised to the power of 0 is 0</li>
<li><code>NA | TRUE</code>, anything else OR <code>TRUE</code> is always <code>TRUE</code></li>
<li><code>NA &amp; FALSE</code>, anything else AND <code>FALSE</code> is always <code>FALSE</code></li>
</ul>
<p><code>NA * 0</code> ? TO DO.</p>
</div>
</div>
<div id="arrange-rows-with-arrange" class="section level2">
<h2><span class="header-section-number">5.3</span> Arrange rows with <code>arrange()</code></h2>
<div id="exercises-8" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Exercises</h3>
<p><em>1 - How could you use <code>arrange()</code> to sort all missing values to the start? (Hint: use <code>is.na()</code>).</em></p>
<p>One way to put missing <code>dep_delay</code> to the start:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, <span class="kw">desc</span>(<span class="kw">is.na</span>(dep_delay))))</code></pre></div>
<pre><code>## # A tibble: 6 x 19
##    year month   day dep_time sched_dep_time dep_delay arr_time
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1  2013     1     1       NA           1630        NA       NA
## 2  2013     1     1       NA           1935        NA       NA
## 3  2013     1     1       NA           1500        NA       NA
## 4  2013     1     1       NA            600        NA       NA
## 5  2013     1     2       NA           1540        NA       NA
## 6  2013     1     2       NA           1620        NA       NA
## # ... with 12 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;</code></pre>
<p><em>2 - Sort <code>flights</code> to find the most delayed flights. Find the flights that left earliest.</em></p>
<p>The top 5 most delayed flights:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, <span class="kw">desc</span>(dep_delay)))</code></pre></div>
<pre><code>## # A tibble: 6 x 19
##    year month   day dep_time sched_dep_time dep_delay arr_time
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1  2013     1     9      641            900      1301     1242
## 2  2013     6    15     1432           1935      1137     1607
## 3  2013     1    10     1121           1635      1126     1239
## 4  2013     9    20     1139           1845      1014     1457
## 5  2013     7    22      845           1600      1005     1044
## 6  2013     4    10     1100           1900       960     1342
## # ... with 12 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;</code></pre>
<p>The top 5 flights that left earliest:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, dep_delay))</code></pre></div>
<pre><code>## # A tibble: 6 x 19
##    year month   day dep_time sched_dep_time dep_delay arr_time
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1  2013    12     7     2040           2123     -43.0       40
## 2  2013     2     3     2022           2055     -33.0     2240
## 3  2013    11    10     1408           1440     -32.0     1549
## 4  2013     1    11     1900           1930     -30.0     2233
## 5  2013     1    29     1703           1730     -27.0     1947
## 6  2013     8     9      729            755     -26.0     1002
## # ... with 12 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;</code></pre>
<p><em>3 - Sort <code>flights</code> to find the fastest flights.</em></p>
<p>Top 5 fastest flights:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, air_time))</code></pre></div>
<pre><code>## # A tibble: 6 x 19
##    year month   day dep_time sched_dep_time dep_delay arr_time
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1  2013     1    16     1355           1315     40.0      1442
## 2  2013     4    13      537            527     10.0       622
## 3  2013    12     6      922            851     31.0      1021
## 4  2013     2     3     2153           2129     24.0      2247
## 5  2013     2     5     1303           1315    -12.0      1342
## 6  2013     2    12     2123           2130    - 7.00     2211
## # ... with 12 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;</code></pre>
<p><em>4 - Which flights travelled the longest? Which travelled the shortest?</em></p>
<p>Top 5 flights that travelled the longest:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, <span class="kw">desc</span>(distance)))</code></pre></div>
<pre><code>## # A tibble: 6 x 19
##    year month   day dep_time sched_dep_time dep_delay arr_time
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1  2013     1     1      857            900    - 3.00     1516
## 2  2013     1     2      909            900      9.00     1525
## 3  2013     1     3      914            900     14.0      1504
## 4  2013     1     4      900            900      0        1516
## 5  2013     1     5      858            900    - 2.00     1519
## 6  2013     1     6     1019            900     79.0      1558
## # ... with 12 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;</code></pre>
<p>Top 5 flights that travelled the shortest:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, distance))</code></pre></div>
<pre><code>## # A tibble: 6 x 19
##    year month   day dep_time sched_dep_time dep_delay arr_time
##   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
## 1  2013     7    27       NA            106     NA          NA
## 2  2013     1     3     2127           2129   -  2.00     2222
## 3  2013     1     4     1240           1200     40.0      1333
## 4  2013     1     4     1829           1615    134        1937
## 5  2013     1     4     2128           2129   -  1.00     2218
## 6  2013     1     5     1155           1200   -  5.00     1241
## # ... with 12 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;</code></pre>
</div>
</div>
<div id="select-columns-with-select" class="section level2">
<h2><span class="header-section-number">5.4</span> Select columns with <code>select()</code></h2>
<div id="exercises-9" class="section level3">
<h3><span class="header-section-number">5.4.1</span> Exercises</h3>
<p><em>1 - Brainstorm as many ways as possible to select <code>dep_time</code>, <code>dep_delay</code>, <code>arr_time</code>, and <code>arr_delay</code> from <code>flights</code>.</em></p>
<p>One way to select those variables is to include each of them in the select function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, dep_time, dep_delay, arr_time, arr_delay)</code></pre></div>
<pre><code>## # A tibble: 336,776 x 4
##    dep_time dep_delay arr_time arr_delay
##       &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1      517      2.00      830     11.0 
##  2      533      4.00      850     20.0 
##  3      542      2.00      923     33.0 
##  4      544     -1.00     1004    -18.0 
##  5      554     -6.00      812    -25.0 
##  6      554     -4.00      740     12.0 
##  7      555     -5.00      913     19.0 
##  8      557     -3.00      709    -14.0 
##  9      557     -3.00      838    - 8.00
## 10      558     -2.00      753      8.00
## # ... with 336,766 more rows</code></pre>
<p>Another way to do it is to use <code>starts_with()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, <span class="kw">starts_with</span>(<span class="st">&#39;dep&#39;</span>), <span class="kw">starts_with</span>(<span class="st">&#39;arr&#39;</span>))</code></pre></div>
<pre><code>## # A tibble: 336,776 x 4
##    dep_time dep_delay arr_time arr_delay
##       &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1      517      2.00      830     11.0 
##  2      533      4.00      850     20.0 
##  3      542      2.00      923     33.0 
##  4      544     -1.00     1004    -18.0 
##  5      554     -6.00      812    -25.0 
##  6      554     -4.00      740     12.0 
##  7      555     -5.00      913     19.0 
##  8      557     -3.00      709    -14.0 
##  9      557     -3.00      838    - 8.00
## 10      558     -2.00      753      8.00
## # ... with 336,766 more rows</code></pre>
<p><em>2 - What happens if you include the name of a variable multiple times in a select() call?</em></p>
<p>The repeated variables will not be included. See below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, dep_time, dep_time, dep_time)</code></pre></div>
<pre><code>## # A tibble: 336,776 x 1
##    dep_time
##       &lt;int&gt;
##  1      517
##  2      533
##  3      542
##  4      544
##  5      554
##  6      554
##  7      555
##  8      557
##  9      557
## 10      558
## # ... with 336,766 more rows</code></pre>
<p><em>3 - What does the <code>one_of()</code> function do? Why might it be helpful in conjunction with this vector?</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vars &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;year&quot;</span>, <span class="st">&quot;month&quot;</span>, <span class="st">&quot;day&quot;</span>, <span class="st">&quot;dep_delay&quot;</span>, <span class="st">&quot;arr_delay&quot;</span>)</code></pre></div>
<p>‘one_of()’ allows you to select variables in the character vector. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, <span class="kw">one_of</span>(vars))</code></pre></div>
<pre><code>## # A tibble: 336,776 x 5
##     year month   day dep_delay arr_delay
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1  2013     1     1      2.00     11.0 
##  2  2013     1     1      4.00     20.0 
##  3  2013     1     1      2.00     33.0 
##  4  2013     1     1     -1.00    -18.0 
##  5  2013     1     1     -6.00    -25.0 
##  6  2013     1     1     -4.00     12.0 
##  7  2013     1     1     -5.00     19.0 
##  8  2013     1     1     -3.00    -14.0 
##  9  2013     1     1     -3.00    - 8.00
## 10  2013     1     1     -2.00      8.00
## # ... with 336,766 more rows</code></pre>
<p>The 5 variables in the vector <code>vars</code> are selected.</p>
<p><em>4 - Does the result of running the following code surprise you? How do the select helpers deal with case by default? How can you change that default?</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, <span class="kw">contains</span>(<span class="st">&quot;TIME&quot;</span>))</code></pre></div>
<pre><code>## # A tibble: 336,776 x 6
##    dep_time sched_dep_time arr_time sched_arr_time air_time
##       &lt;int&gt;          &lt;int&gt;    &lt;int&gt;          &lt;int&gt;    &lt;dbl&gt;
##  1      517            515      830            819    227  
##  2      533            529      850            830    227  
##  3      542            540      923            850    160  
##  4      544            545     1004           1022    183  
##  5      554            600      812            837    116  
##  6      554            558      740            728    150  
##  7      555            600      913            854    158  
##  8      557            600      709            723     53.0
##  9      557            600      838            846    140  
## 10      558            600      753            745    138  
## # ... with 336,766 more rows, and 1 more variable: time_hour &lt;dttm&gt;</code></pre>
<p>The original code intends to select variables containing the characters <code>TIME</code>. However, the selected variables contain the lower case <code>time</code> instead. By default, <code>contains()</code> is not case sensitive. To override this behaviour, we can use <code>ignore.case = FALSE</code>. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, <span class="kw">contains</span>(<span class="st">&quot;TIME&quot;</span>, <span class="dt">ignore.case =</span> <span class="ot">FALSE</span>))</code></pre></div>
<pre><code>## # A tibble: 336,776 x 0</code></pre>
<p>In this case, no variables are being selected because none of the variables contain the character string <code>TIME</code>.</p>
</div>
</div>
<div id="add-new-variables-with-mutate" class="section level2">
<h2><span class="header-section-number">5.5</span> Add new variables with <code>mutate()</code></h2>
<div id="exercises-10" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Exercises</h3>
<p><em>1 - Currently <code>dep_time</code> and <code>sched_dep_time</code> are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights &lt;-<span class="st"> </span><span class="kw">mutate</span>(flights,
                  <span class="dt">dep_time_mins =</span> dep_time <span class="op">%/%</span><span class="st"> </span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span><span class="st"> </span>dep_time <span class="op">%%</span><span class="st"> </span><span class="dv">100</span>,
                  <span class="dt">sched_dep_time_mins =</span> sched_dep_time <span class="op">%/%</span><span class="st"> </span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span>
<span class="st">                    </span>sched_dep_time <span class="op">%%</span><span class="st"> </span><span class="dv">100</span>)

<span class="kw">select</span>(flights, <span class="kw">starts_with</span>(<span class="st">&#39;dep_time&#39;</span>), <span class="kw">starts_with</span>(<span class="st">&#39;sched&#39;</span>))</code></pre></div>
<pre><code>## # A tibble: 336,776 x 5
##    dep_time dep_time_mins sched_dep_time sched_arr_time sched_dep_time_mi~
##       &lt;int&gt;         &lt;dbl&gt;          &lt;int&gt;          &lt;int&gt;              &lt;dbl&gt;
##  1      517           317            515            819                315
##  2      533           333            529            830                329
##  3      542           342            540            850                340
##  4      544           344            545           1022                345
##  5      554           354            600            837                360
##  6      554           354            558            728                358
##  7      555           355            600            854                360
##  8      557           357            600            723                360
##  9      557           357            600            846                360
## 10      558           358            600            745                360
## # ... with 336,766 more rows</code></pre>
<p><em>2 - Compare <code>air_time</code> with <code>arr_time - dep_time</code>. What do you expect to see? What do you see? What do you need to do to fix it?</em></p>
<p><code>air_time</code> is the amount of time spent in the air in minutes, and we would expect to see <code>air_time</code> and <code>arr_time - dep_time</code> to be the same. First, let’s define a new variable <code>flight_time</code> as the difference between <code>arr_time</code> and <code>dep_time</code>. Comparing it with <code>air_time</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">flight_time =</span> arr_time <span class="op">-</span><span class="st"> </span>dep_time) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(air_time, flight_time)</code></pre></div>
<pre><code>## # A tibble: 336,776 x 2
##    air_time flight_time
##       &lt;dbl&gt;       &lt;int&gt;
##  1    227           313
##  2    227           317
##  3    160           381
##  4    183           460
##  5    116           258
##  6    150           186
##  7    158           358
##  8     53.0         152
##  9    140           281
## 10    138           195
## # ... with 336,766 more rows</code></pre>
<p>The computed <code>flight_time</code> is very different from <code>air_time</code>. The difference is mainly due to the fact that the original <code>arr_time</code> and <code>dep_time</code> are not really continuous numbers. To remedy this, <code>arr_time</code> is converted to minutes since midnight, same as previous question, and then <code>flight_time</code> is recalculated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights &lt;-<span class="st"> </span><span class="kw">mutate</span>(flights,
                  <span class="dt">arr_time_mins =</span> arr_time <span class="op">%/%</span><span class="st"> </span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="dv">60</span> <span class="op">+</span><span class="st"> </span>arr_time <span class="op">%%</span><span class="st"> </span><span class="dv">100</span>)

flights &lt;-<span class="st"> </span><span class="kw">mutate</span>(flights, <span class="dt">flight_time =</span> arr_time_mins <span class="op">-</span><span class="st"> </span>dep_time_mins)

<span class="kw">select</span>(flights, air_time, flight_time)</code></pre></div>
<pre><code>## # A tibble: 336,776 x 2
##    air_time flight_time
##       &lt;dbl&gt;       &lt;dbl&gt;
##  1    227         193  
##  2    227         197  
##  3    160         221  
##  4    183         260  
##  5    116         138  
##  6    150         106  
##  7    158         198  
##  8     53.0        72.0
##  9    140         161  
## 10    138         115  
## # ... with 336,766 more rows</code></pre>
<p>Again, we see the given <code>air_time</code> is different from the computed <code>flight_time</code>. In fact, only 196 flights have the same <code>air_time</code> and computed <code>flight_time</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(flights<span class="op">$</span>air_time <span class="op">==</span><span class="st"> </span>flights<span class="op">$</span>flight_time, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 196</code></pre>
<p><em>3 - Compare <code>dep_time</code>, <code>sched_dep_time</code>, and <code>dep_delay</code>. How would you expect those three numbers to be related?</em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(flights, dep_time, sched_dep_time, dep_delay)</code></pre></div>
<pre><code>## # A tibble: 336,776 x 3
##    dep_time sched_dep_time dep_delay
##       &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;
##  1      517            515      2.00
##  2      533            529      4.00
##  3      542            540      2.00
##  4      544            545     -1.00
##  5      554            600     -6.00
##  6      554            558     -4.00
##  7      555            600     -5.00
##  8      557            600     -3.00
##  9      557            600     -3.00
## 10      558            600     -2.00
## # ... with 336,766 more rows</code></pre>
<p><code>dep_time</code> and <code>sched_dep_time</code> are in clock format. Their difference in minutes is given by <code>dep_delay</code>.</p>
<p><em>4 - Find the 10 most delayed flights using a ranking function. How do you want to handle ties? Carefully read the documentation for <code>min_rank()</code></em></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(<span class="kw">arrange</span>(flights, <span class="kw">min_rank</span>(<span class="kw">desc</span>(dep_delay))), <span class="dv">10</span>)</code></pre></div>
<pre><code>## # A tibble: 10 x 23
##     year month   day dep_time sched_dep_time dep_delay arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;
##  1  2013     1     9      641            900      1301     1242
##  2  2013     6    15     1432           1935      1137     1607
##  3  2013     1    10     1121           1635      1126     1239
##  4  2013     9    20     1139           1845      1014     1457
##  5  2013     7    22      845           1600      1005     1044
##  6  2013     4    10     1100           1900       960     1342
##  7  2013     3    17     2321            810       911      135
##  8  2013     6    27      959           1900       899     1236
##  9  2013     7    22     2257            759       898      121
## 10  2013    12     5      756           1700       896     1058
## # ... with 16 more variables: sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;,
## #   time_hour &lt;dttm&gt;, dep_time_mins &lt;dbl&gt;, sched_dep_time_mins &lt;dbl&gt;,
## #   arr_time_mins &lt;dbl&gt;, flight_time &lt;dbl&gt;</code></pre>
<p><code>min_rank()</code> is equivalent to <code>rank()</code> method with the argument <code>ties.method = 'min</code>. It assigns every tied element to the lowest rank.</p>
<p><em>5 - What does <code>1:3 + 1:10</code> return? Why?</em></p>
<p>R performs vectorized calculations. For example, when we add two vectors of the same length together, <code>c(1,2,3) + c(4,5,6)</code>, the result will be <code>c(5,7,9)</code>. When we add two vectors of different lengths, the shorter vector with be ‘repeated’ to match the length of the longer vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">:</span><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span></code></pre></div>
<pre><code>## Warning in 1:3 + 1:10: longer object length is not a multiple of shorter
## object length</code></pre>
<pre><code>##  [1]  2  4  6  5  7  9  8 10 12 11</code></pre>
<p><em>6 - What trigonometric functions does R provide?</em></p>
<p>Type <code>?sin</code> to see a complete list of trignomometric functions.</p>
</div>
</div>
<div id="grouped-summaries-with-summarise" class="section level2">
<h2><span class="header-section-number">5.6</span> Grouped summaries with <code>summarise()</code></h2>
<div id="exercises-11" class="section level3">
<h3><span class="header-section-number">5.6.1</span> Exercises</h3>
<p><em>1 - Brainstorm at least 5 different ways to assess the typical delay characteristics of a group of flights. Consider the following scenarios:</em></p>
<p><em>- A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of the time.</em></p>
<p><em>- A flight is always 10 minutes late.</em></p>
<p><em>- A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of the time.</em></p>
<p><em>- 99% of the time a flight is on time. 1% of the time it’s 2 hours late.</em></p>
<p><em>Which is more important: arrival delay or departure delay?</em></p>
<p>Just some personal and non-scientific reasoning, to me, arrival delay is more important than departure delay.</p>
<p><em>2 - Come up with another approach that will give you the same output as <code>not_cancelled %&gt;% count(dest)</code> and <code>not_cancelled %&gt;% count(tailnum, wt = distance)</code> (without using <code>count()</code>).</em></p>
<p>We can use <code>n()</code> instead in <code>summarize()</code> to obtain the same output as <code>not_cancelled %&gt;% count(dest)</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay), <span class="op">!</span><span class="kw">is.na</span>(arr_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(dest) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">n</span>())</code></pre></div>
<pre><code>## # A tibble: 104 x 2
##    dest  count
##    &lt;chr&gt; &lt;int&gt;
##  1 ABQ     254
##  2 ACK     264
##  3 ALB     418
##  4 ANC       8
##  5 ATL   16837
##  6 AUS    2411
##  7 AVL     261
##  8 BDL     412
##  9 BGR     358
## 10 BHM     269
## # ... with 94 more rows</code></pre>
<p>And for <code>not_cancelled %&gt;% count(tailnum, wt = distance)</code>, we group by <code>tailnum</code> and sum the distance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay), <span class="op">!</span><span class="kw">is.na</span>(arr_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(tailnum) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">sum</span>(distance))</code></pre></div>
<pre><code>## # A tibble: 4,037 x 2
##    tailnum  count
##    &lt;chr&gt;    &lt;dbl&gt;
##  1 D942DN    3418
##  2 N0EGMQ  239143
##  3 N10156  109664
##  4 N102UW   25722
##  5 N103US   24619
##  6 N104UW   24616
##  7 N10575  139903
##  8 N105UW   23618
##  9 N107US   21677
## 10 N108UW   32070
## # ... with 4,027 more rows</code></pre>
<p><em>3 - Our definition of cancelled flights <code>(is.na(dep_delay) | is.na(arr_delay) )</code> is slightly suboptimal. Why? Which is the most important column?</em></p>
<p>Let’s see how ‘cancelled flights’ are defined in the <code>flights</code> dataset. Natrually one would think that cancelled flights are those that never departed from the origins and never arrived at the destinations. Checking the NA counts in those columns:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">starts_with</span>(<span class="st">&quot;dep&quot;</span>), <span class="kw">starts_with</span>(<span class="st">&quot;arr&quot;</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">sapply</span>(<span class="cf">function</span>(x){<span class="kw">sum</span>(<span class="kw">is.na</span>(x))})</code></pre></div>
<pre><code>##      dep_time     dep_delay dep_time_mins      arr_time     arr_delay 
##          8255          8255          8255          8713          9430 
## arr_time_mins 
##          8713</code></pre>
<p>We see that the NA counts for <code>dep_time</code> and <code>arr_time</code> don’t match. The difference is <code>8713 - 8255 = 458</code>. One possible explanation is that those flights did actually take off, but arrived at a different airport or were forced to return to the origins. To confirm my hypothesis, we can look at the number of observations with non missing departure time and missing arrival time:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nrow</span>(flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_time), <span class="kw">is.na</span>(arr_time)))</code></pre></div>
<pre><code>## [1] 458</code></pre>
<p>The NA count for <code>arr_delay</code> is a bit mysterious. A closer look at the <code>flights</code> dataset reveals that the NA count for <code>arr_delay</code> is the same as the NA count for <code>air_time</code>. There were flights that did depart and arrive, but with missing <code>air_time</code> and <code>arr_delay</code>.</p>
<p>So my conclusion is, depending on how you define cancelled flights (never departed from the origin or never arrived at the destination), <code>dep_time</code> or <code>arr_time</code> should be used to filter cancelled flights.</p>
<p><em>4 - Look at the number of cancelled flights per day. Is there a pattern? Is the proportion of cancelled flights related to the average delay?</em></p>
<p>Here, I define cancelled flights as those never departed at the origin in the first place. As can be seen in the plot below, there is a positive linear trend.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(month, day) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_dep_delay =</span> <span class="kw">mean</span>(dep_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),
            <span class="dt">prop_cancelled =</span> <span class="kw">sum</span>(<span class="kw">is.na</span>(dep_time)<span class="op">/</span><span class="kw">n</span>())) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> avg_dep_delay, <span class="dt">y =</span> prop_cancelled)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p><img src="R4DS_bookdown_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
<p><em>5 - Which carrier has the worst delays? Challenge: can you disentangle the effects of bad airports vs. bad carriers? Why/why not? (Hint: think about <code>flights %&gt;% group_by(carrier, dest) %&gt;% summarise(n())</code>)</em></p>
<p>First we need to decide how we quantify and compare delays between carriers. For this question we’ll just simply calculate the average minutes in arrival and departure delays.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">worst &lt;-<span class="st"> </span>flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(carrier) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_arr_delay =</span> <span class="kw">mean</span>(arr_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),
            <span class="dt">avg_dep_delay =</span> <span class="kw">mean</span>(dep_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</code></pre></div>
<p>Arrange by average arrival delay in minutes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">arrange</span>(worst, <span class="kw">desc</span>(avg_arr_delay))</code></pre></div>
<pre><code>## # A tibble: 16 x 3
##    carrier avg_arr_delay avg_dep_delay
##    &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
##  1 F9             21.9           20.2 
##  2 FL             20.1           18.7 
##  3 EV             15.8           20.0 
##  4 YV             15.6           19.0 
##  5 OO             11.9           12.6 
##  6 MQ             10.8           10.6 
##  7 WN              9.65          17.7 
##  8 B6              9.46          13.0 
##  9 9E              7.38          16.7 
## 10 UA              3.56          12.1 
## 11 US              2.13           3.78
## 12 VX              1.76          12.9 
## 13 DL              1.64           9.26
## 14 AA              0.364          8.59
## 15 HA            - 6.92           4.90
## 16 AS            - 9.93           5.80</code></pre>
<p>Arrange by average departure delay in minutes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">arrange</span>(worst, <span class="kw">desc</span>(avg_dep_delay))</code></pre></div>
<pre><code>## # A tibble: 16 x 3
##    carrier avg_arr_delay avg_dep_delay
##    &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;
##  1 F9             21.9           20.2 
##  2 EV             15.8           20.0 
##  3 YV             15.6           19.0 
##  4 FL             20.1           18.7 
##  5 WN              9.65          17.7 
##  6 9E              7.38          16.7 
##  7 B6              9.46          13.0 
##  8 VX              1.76          12.9 
##  9 OO             11.9           12.6 
## 10 UA              3.56          12.1 
## 11 MQ             10.8           10.6 
## 12 DL              1.64           9.26
## 13 AA              0.364          8.59
## 14 AS            - 9.93           5.80
## 15 HA            - 6.92           4.90
## 16 US              2.13           3.78</code></pre>
<p>Similarly we can look at which airport has the worst departure delay:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(origin) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_dep_delay =</span> <span class="kw">mean</span>(dep_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) </code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   origin avg_dep_delay
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 EWR             15.1
## 2 JFK             12.1
## 3 LGA             10.3</code></pre>
<p>and the worst arrival delay:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(origin) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_arr_delay =</span> <span class="kw">mean</span>(arr_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) </code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   origin avg_arr_delay
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 EWR             9.11
## 2 JFK             5.55
## 3 LGA             5.78</code></pre>
<p>We can attempt to disentangle the effects of departure delay for carrier <code>9E</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(carrier, origin) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_dep_delay =</span> <span class="kw">mean</span>(dep_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(carrier <span class="op">==</span><span class="st"> &#39;9E&#39;</span>)</code></pre></div>
<pre><code>## # A tibble: 3 x 3
## # Groups:   carrier [1]
##   carrier origin avg_dep_delay
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 9E      EWR             5.95
## 2 9E      JFK            19.0 
## 3 9E      LGA             8.89</code></pre>
<p>The overall average departure delay is 16.73 minutes from the previous table. However, we can conclude that at least for carrier <code>9E</code>, on average, the flights were delayed most at JFK.</p>
<p><em>6 - What does the sort argument to count() do. When might you use it?</em></p>
<p>The <code>sort</code> argument if set to <code>TRUE</code>, will sort the output in descending order. For example, without <code>sort = TRUE</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay), <span class="op">!</span><span class="kw">is.na</span>(arr_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(dest)</code></pre></div>
<pre><code>## # A tibble: 104 x 2
##    dest      n
##    &lt;chr&gt; &lt;int&gt;
##  1 ABQ     254
##  2 ACK     264
##  3 ALB     418
##  4 ANC       8
##  5 ATL   16837
##  6 AUS    2411
##  7 AVL     261
##  8 BDL     412
##  9 BGR     358
## 10 BHM     269
## # ... with 94 more rows</code></pre>
<p>With <code>sort = TRUE</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay), <span class="op">!</span><span class="kw">is.na</span>(arr_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">count</span>(dest, <span class="dt">sort =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## # A tibble: 104 x 2
##    dest      n
##    &lt;chr&gt; &lt;int&gt;
##  1 ATL   16837
##  2 ORD   16566
##  3 LAX   16026
##  4 BOS   15022
##  5 MCO   13967
##  6 CLT   13674
##  7 SFO   13173
##  8 FLL   11897
##  9 MIA   11593
## 10 DCA    9111
## # ... with 94 more rows</code></pre>
</div>
</div>
<div id="grouped-mutates-and-filters" class="section level2">
<h2><span class="header-section-number">5.7</span> Grouped mutates (and filters)</h2>
<div id="exercises-12" class="section level3">
<h3><span class="header-section-number">5.7.1</span> Exercises</h3>
<p><em>1 - Refer back to the lists of useful mutate and filtering functions. Describe how each operation changes when you combine it with grouping.</em></p>
<p>Before grouping, functions like <code>mean()</code>, <code>median()</code>, <code>min()</code>, or <code>max()</code> will operation over the whole dataset. For example, applying <code>mean()</code> on a variable before grouping will get the average of the variable over the entire dataset.</p>
<p>After grouping, these functions will operate within each group.</p>
<p><em>2 - Which plane (<code>tailnum</code>) has the worst on-time record?</em></p>
<p>Filter out the on-time departure records and calculate the average departure delay in minutes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(tailnum) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(dep_delay <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_delay =</span> <span class="kw">mean</span>(dep_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(avg_delay))</code></pre></div>
<pre><code>## # A tibble: 3,885 x 2
##    tailnum avg_delay
##    &lt;chr&gt;       &lt;dbl&gt;
##  1 N844MH        297
##  2 N452UW        291
##  3 N922EV        274
##  4 N587NW        272
##  5 N911DA        268
##  6 N665MQ        268
##  7 N673MQ        257
##  8 N851NW        233
##  9 N654UA        227
## 10 N550NW        212
## # ... with 3,875 more rows</code></pre>
<p><em>3 - What time of day should you fly if you want to avoid delays as much as possible?</em></p>
<p>Similar to above question, we filter out the on-time departures and calculate the average departure delay in minuts for each hour.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span> (dep_delay <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(hour) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">avg_delay =</span> <span class="kw">mean</span>(dep_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(avg_delay)</code></pre></div>
<pre><code>## # A tibble: 19 x 2
##     hour avg_delay
##    &lt;dbl&gt;     &lt;dbl&gt;
##  1  5.00      15.3
##  2  7.00      24.1
##  3  6.00      24.2
##  4  9.00      29.7
##  5  8.00      29.9
##  6 12.0       32.3
##  7 11.0       32.5
##  8 10.0       32.6
##  9 13.0       33.5
## 10 14.0       37.1
## 11 23.0       38.0
## 12 15.0       38.8
## 13 16.0       43.4
## 14 17.0       45.3
## 15 18.0       46.5
## 16 22.0       46.5
## 17 20.0       49.6
## 18 21.0       50.3
## 19 19.0       51.1</code></pre>
<p><em>4 - For each destination, compute the total minutes of delay. For each flight, compute the proportion of the total delay for its destination.</em></p>
<p>We select only <code>dest</code> and <code>arr_delay</code> variables. We also filter out on-time flights or flights that were cancelled.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(dest, arr_delay) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(dest) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(arr_delay <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total_delay =</span> <span class="kw">sum</span>(arr_delay, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),
         <span class="dt">prop_delay =</span> arr_delay <span class="op">/</span><span class="st"> </span>total_delay)</code></pre></div>
<pre><code>## # A tibble: 133,004 x 4
## # Groups:   dest [103]
##    dest  arr_delay total_delay prop_delay
##    &lt;chr&gt;     &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
##  1 IAH       11.0        99391  0.000111 
##  2 IAH       20.0        99391  0.000201 
##  3 MIA       33.0       140424  0.000235 
##  4 ORD       12.0       283046  0.0000424
##  5 FLL       19.0       202605  0.0000938
##  6 ORD        8.00      283046  0.0000283
##  7 LAX        7.00      203226  0.0000344
##  8 DFW       31.0       110009  0.000282 
##  9 ATL       12.0       300299  0.0000400
## 10 DTW       16.0       138258  0.000116 
## # ... with 132,994 more rows</code></pre>
<p><em>5 - Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using <code>lag()</code> explore how the delay of a flight is related to the delay of the immediately preceding flight.</em></p>
<p>Let’s focus on flights departing from <code>JFK</code> and assume we can ignore the effect of cancelled flights:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &#39;JFK&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pre_dep_delay =</span> <span class="kw">lag</span>(dep_delay, <span class="dt">default =</span> <span class="dv">0</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> dep_delay, <span class="dt">y=</span> pre_dep_delay)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> .<span class="dv">5</span>)</code></pre></div>
<p><img src="R4DS_bookdown_files/figure-html/unnamed-chunk-98-1.png" width="672" /></p>
<p>The mass of data on the bottom left shows that the departure delay and the previous depart delay are related. The correlation is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights &lt;-<span class="st"> </span>flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &#39;JFK&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">pre_dep_delay =</span> <span class="kw">lag</span>(dep_delay, <span class="dt">default =</span> <span class="dv">0</span>))

<span class="kw">cor</span>(flights<span class="op">$</span>dep_delay, flights<span class="op">$</span>pre_dep_delay)</code></pre></div>
<pre><code>## [1] 0.2928064</code></pre>
<p><em>6 - Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?</em></p>
<p>To find flights that are suspiciously fast, in other words, outliers that are far below than the average <code>air_time</code>, we can compute z-score, or the number of standard deviations below/above the mean <code>air_time</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(air_time)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(dest) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">air_time_mean =</span> <span class="kw">mean</span>(air_time),
         <span class="dt">air_time_sd =</span> <span class="kw">sd</span>(air_time),
         <span class="dt">z =</span> (air_time <span class="op">-</span><span class="st"> </span>air_time_mean) <span class="op">/</span><span class="st"> </span>air_time_sd) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(z, air_time_mean, dest, <span class="kw">everything</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(z)</code></pre></div>
<pre><code>## # A tibble: 109,079 x 27
## # Groups:   dest [70]
##        z air_time_mean dest   year month   day dep_time sched_dep_time
##    &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;
##  1 -4.10          57.1 BUF    2013    11    10     2307           2250
##  2 -3.80          51.9 ROC    2013     3    25     2340           2250
##  3 -3.55         329   SEA    2013     7     3     1533           1459
##  4 -3.51          52.6 ORF    2013    11     3     1720           1645
##  5 -3.40          66.5 PIT    2013     7    17     1504           1505
##  6 -3.03          66.5 PIT    2013     5     8     1947           1859
##  7 -3.03         329   SEA    2013     5     6     1728           1730
##  8 -2.99         331   PDX    2013     5     6     1753           1755
##  9 -2.98         329   LAX    2013     9     6     2042           2025
## 10 -2.97         329   SEA    2013     5     6     1553           1557
## # ... with 109,069 more rows, and 19 more variables: dep_delay &lt;dbl&gt;,
## #   arr_time &lt;int&gt;, sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;,
## #   flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, air_time &lt;dbl&gt;,
## #   distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;,
## #   dep_time_mins &lt;dbl&gt;, sched_dep_time_mins &lt;dbl&gt;, arr_time_mins &lt;dbl&gt;,
## #   flight_time &lt;dbl&gt;, pre_dep_delay &lt;dbl&gt;, air_time_sd &lt;dbl&gt;</code></pre>
<p>I would say that <code>air_time</code> that are 2 standard deviations below the are unusually fast.</p>
<p>Similarly we can look at which flights are most delayed in the air.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(air_time)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(dest) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">air_time_mean =</span> <span class="kw">mean</span>(air_time),
         <span class="dt">air_time_sd =</span> <span class="kw">sd</span>(air_time),
         <span class="dt">z =</span> (air_time <span class="op">-</span><span class="st"> </span>air_time_mean) <span class="op">/</span><span class="st"> </span>air_time_sd) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(z, air_time_mean, dest, <span class="kw">everything</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(z))</code></pre></div>
<pre><code>## # A tibble: 109,079 x 27
## # Groups:   dest [70]
##        z air_time_mean dest   year month   day dep_time sched_dep_time
##    &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;
##  1 13.9           44.5 SYR    2013     9     1     2237           1711
##  2 12.2           42.1 ACK    2013     6    29      755            800
##  3 11.8           38.5 BOS    2013     7    23     1617           1605
##  4 10.8           38.5 BOS    2013     7    23     1200           1200
##  5 10.4           71.9 RDU    2013     9     1     1719           1712
##  6 10.3           57.1 BUF    2013    12    16      923            925
##  7  9.91          87.6 DTW    2013     7    27     1654           1620
##  8  9.74          38.5 BOS    2013     2    17      841            840
##  9  9.74          38.5 BOS    2013     7    23     1242           1245
## 10  9.69          51.9 ROC    2013     7    10     2350           2030
## # ... with 109,069 more rows, and 19 more variables: dep_delay &lt;dbl&gt;,
## #   arr_time &lt;int&gt;, sched_arr_time &lt;int&gt;, arr_delay &lt;dbl&gt;, carrier &lt;chr&gt;,
## #   flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, air_time &lt;dbl&gt;,
## #   distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;,
## #   dep_time_mins &lt;dbl&gt;, sched_dep_time_mins &lt;dbl&gt;, arr_time_mins &lt;dbl&gt;,
## #   flight_time &lt;dbl&gt;, pre_dep_delay &lt;dbl&gt;, air_time_sd &lt;dbl&gt;</code></pre>
<p>10 standard deviations above the mean!</p>
<p><em>7 - Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.</em></p>
<p>Destinations that are flown by the most number of carriers:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(dest) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_carrier =</span> <span class="kw">length</span>(<span class="kw">unique</span>(carrier))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(num_carrier <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(num_carrier))</code></pre></div>
<pre><code>## # A tibble: 45 x 2
##    dest  num_carrier
##    &lt;chr&gt;       &lt;int&gt;
##  1 LAX             5
##  2 SFO             5
##  3 TPA             5
##  4 AUS             4
##  5 BOS             4
##  6 LAS             4
##  7 PIT             4
##  8 ATL             3
##  9 BNA             3
## 10 CLT             3
## # ... with 35 more rows</code></pre>
<p>Similiar, we can rank the carriers by counting how many destinations they fly to:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(carrier) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_dest =</span> <span class="kw">length</span>(<span class="kw">unique</span>(dest))) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(num_dest <span class="op">&gt;=</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(num_dest))</code></pre></div>
<pre><code>## # A tibble: 9 x 2
##   carrier num_dest
##   &lt;chr&gt;      &lt;int&gt;
## 1 B6            42
## 2 9E            34
## 3 DL            29
## 4 AA            17
## 5 MQ            11
## 6 VX             5
## 7 EV             3
## 8 US             3
## 9 UA             2</code></pre>
<p><em>8 - For each plane, count the number of flights before the first delay of greater than 1 hour.</em></p>
<p>Not sure if this is the most elegant solution. Let’s assume we can ignore the cancelled flights. We group by <code>tailnum</code>, and use <code>cummax()</code> to find the cummulative maxium departure delay. Count the total number of observations with cummulative max less than 60.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">flights <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(dep_delay)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(tailnum) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">max_delay =</span> <span class="kw">cummax</span>(dep_delay),
         <span class="dt">less_one_hour =</span> max_delay <span class="op">&lt;</span><span class="st"> </span><span class="dv">60</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">count =</span> <span class="kw">sum</span>(less_one_hour)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(count))</code></pre></div>
<pre><code>## # A tibble: 1,957 x 2
##    tailnum count
##    &lt;chr&gt;   &lt;int&gt;
##  1 N705TW    159
##  2 N706TW    149
##  3 N713TW    128
##  4 N721TW    120
##  5 N5FAAA    117
##  6 N3769L    104
##  7 N804JB    104
##  8 N3748Y    103
##  9 N645JB     94
## 10 N3742C     91
## # ... with 1,947 more rows</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="workflow-basics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="workflow-scripts.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["R4DS bookdown.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
